### ISSUE TITLE
 Firefox can't establish a connection to the server at ws://x.x.x.x/ws_client.1 loader.js

### ISSUE THREAD

**Issue by ewwink** [hola/cdn#4]
in browser console I see
 

> Firefox can't establish a connection to the server at ws://x.x.x.x/ws_client.1 loader.js

also get this

> GET http://198.x.x.x/ws_client  [HTTP/1.1 403 Forbidden 679ms]

is it normal?

**Comment by boyang-hola** [comment]
Hi,
Please provide a bit more detail. Can you provide the full console output. Which line initiates the request?
Did you include your customer id to the script?

**Comment by boyang-hola** [comment]
The message indicates a failed web sockets connection. We use websockets for passing extra information between clients and servers - but it's not required for proper functionality. These web sockets sometimes fail to connect but have no influence on functionality

**Comment by boyang-hola** [comment]
A printout has been added to indicate that websocket temporary connection failures are immaterial
